apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-mem-cpu-example
spec:
    hard:
      cpu: "5"
      memory: 10Gi
      pods: "10"
    scopeSelector:
      matchExpressions:
        - operator: In
          scopeName: PriorityClass
          values: [ "low" ]