apiVersion: v1
kind: Service
metadata:
  labels:
    app: heroes-service
  name: heroes-service
  namespace: example-k8s
spec:
  ports:
    - nodePort: 30001 # Access Port
      port: 8080 # Maaping port with container
      protocol: TCP
      targetPort: 8080
  selector:
    app: heroes-service
  type: NodePort